* Recipes to print barcode labels using [[http://www.reportlab.com/software/opensource/][reportlab]] 

I am a little amazed that I can't find a simple database of label metrics to
make PDFs for printing. That is Avery, Herma, etc. make and sell blank label
forms, for which a PDF can be created in order to print onto the blank label
forms. How do people do inventory managment with open source software?

My needs are minimal but hopefully someone will tell me where to find
all of these metrics or that someone has a similar open source software
package. For now, I will publish this poor code.

* Usage
For now, I use this simple python module as such:

#+BEGIN_SRC shell
python generate_barcode_simple.py --codes '["Box{:=04}".format(i) for i in range(no_labels_x * no_labels_y + 1)[1:]]' \
       --encode Code128 --recipe avery_3475 --filename barcodes.pdf
#+END_SRC

For single encodings:
#+BEGIN_SRC shell
python create_single_barcode.py -c 'do crap' -x 5 -y 3
#+END_SRC

List available =recipes=:
#+BEGIN_SRC shell
generate_barcode_simple.py --list-recipes
#+END_SRC

List available =encoders=:
#+BEGIN_SRC shell
generate_barcode_simple.py -le
#+END_SRC

** TODO Implement the following functionality:
   - [X] better positioning of text below =code=
   - [X] different paper sizes than A4, which depend on [[file:recipe_database.py][recipe]] 
   - [X] Complete command line options
   - [ ] Different output formats for single barcode script
   - [ ] Allow linking to inventory to rely on pool
   - [ ] implement tests


* Contributions, please

My ability to design software is underdeveloped and correlates with my
needs. Please fork this repository or contribute metrics, if you find it
useful. My previous self would appreciate it.
